GET https://currency-conversion-and-exchange-rates.p.rapidapi.com/convert?from=USD&to=EUR&amount=750
x-rapidapi-key: fbb0077ff6mshe69fa543fd74042p15bde4jsn7c79a68f983d

GET https://wft-geo-db.p.rapidapi.com/v1/geo/countries/US/regions
x-rapidapi-key: fbb0077ff6mshe69fa543fd74042p15bde4jsn7c79a68f983d

